### ISSUE TITLE
RFC: changing type-composition from "Foo(Bar)" to "Foo<Bar>"

### ISSUE THREAD

**Issue by knocte** [ivy-lang/ivy-bitcoin#13]
By looking at the PreImage example from the docs I've realised there's this special type called `Sha256(Bytes)`.

First, I'm wondering, is this type just acting as a keyword, or does ivy actually parse the parenthesis to find a type composition between `Sha256` and `Bytes`?

If it's the latter, I would recommend changing the character for this kind of type composition to use `<>` instead of `()`, so instead of `Sha256(Bytes)` it would be `Sha256<Bytes>`.

Main motivations:
- It would read a bit cleaner, since there's less need for the eye to "compute" nested parenthesis.
- It resembles generics notation in languages such as C#, Java, F#, etc.
- It potentially simplifies the implementation of the compiler? Given that parenthesis characters would have one less function.

Any feedback welcome.

**Comment by danrobinson** [comment]
Yes, Ivy parses the parentheses (so you can have arbitrarily nested types, like `Sha256(Sha256(Sha1(PublicKey)))`).

I prefer parentheses to angle brackets because that's Ivy's convention for function application, and really this is supposed to evoke that the type `Sha256(Sha1(Bytes))` represents the application of the `sha256` function to the result of applying the `sha1` function to a bytestring. Additionally, you can think of `Sha256` as a function that takes a type like `Bytes` or `PublicKey` and turns it into a new type (like `Sha256(Bytes)` or `Sha256(PublicKey)`). We thought about angle brackets but ultimately it would be adding a little extra syntax to the language when it's not necessary. Finally, angle brackets look a little ugly. 

(I don't know any other language that use parentheses for type parameterization, but languages like Haskell use the same conventions for type parameterization as for function application—i.e., just a space).

As for the implementation of the parser, this wouldn't make that any more or less complicated, because there's never ambiguity in whether you're expecting to see a type or a value.

**Comment by knocte** [comment]
Fair enough!
