### ISSUE TITLE
Ability to generate BCH addresses

### ISSUE THREAD

**Issue by dymurray** [ivy-lang/ivy-bitcoin#6]
I would like to generate a valid BCH address in Ivy. Do you have any plans to support this and if you do is there a workaround I could test out?

Thanks,
Dylan

**Comment by danrobinson** [comment]
All Bitcoin addresses created by the Ivy playground and SDK are SegWit addresses, which are not properly supported by Bitcoin Cash (they are effectively treated as anyone-can-spend addresses, although to spend them you need to know the redeem script). We don't have any plans to support non-SegWit addresses, since such addresses allow transaction malleability, thus foreclosing some of the more interesting things we would like to do with Ivy for Bitcoin.

**Comment by Kinnardian** [comment]
Maybe create a fork @dymurray ?
